name: gpt2
hf_path: gpt2
hidden_size: 768
target_layer: -1  # -1 means final layer

# Training parameters
learning_rate: 1e-4
weight_decay: 0.01
warmup_steps: 100
max_grad_norm: 1.0

# Fine-tuning
epochs_per_cycle: 3
gradient_accumulation_steps: 1
