name: sst2
hf_path: glue
hf_name: sst2
num_classes: 2

# For classification head
text_column: sentence
label_column: label

# Training parameters
batch_size: 32
max_length: 128
num_workers: 4

# Validation split
validation_split: 0.1
